### ISSUE TITLE
search bar

### ISSUE THREAD

**Issue by mightyGaby** [datamade/million-dollar-blocks#17]
Hey there! I know you are still working on this and I'm jumping the "open source" gun a little, but I've done some work with leaflet/mapbox and can pretty easily add a search bar next to the toggle buttons for "drug-related" vs. "all crimes" so that users can type in an address or place and have the map zoom in to that area...let me know if that is something you'd be interested in!

**Comment by cathydeng** [comment]
hey Gaby - I'm reluctant to have a search bar since the point is to focus on the few neighborhoods that do have excessive incarceration spending, & b/c the page is already very cluttered. also reluctant to introduce new code at the last minute.

thank you for the offer, though! :heart:

if you'd like to help out, it'd be really useful to have another set of eyes hunting down grammar/spelling errors & awkward sentence wording.

**Comment by mightyGaby** [comment]
absolutely!

Gabrielle Ruiz-Funes
github.com/mightyGaby
847-922-2290

_Northwestern University, Segal Design Institute & McCormick School of
Engineering_BS, Manufacturing and Design Engineering
BS, Industrial Engineering and Management Sciences
